name: Test SDK composer package

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ 8.0 ]

    steps:
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install Composer dependencies
        working-directory: ./example
        run: composer install

      - name: Run SDK test
        working-directory: ./example
        run: php Base.php
        env:
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          CHANNEL_NAME: ${{ secrets.CHANNEL_NAME }}
          CHANNEL_PASSKEY: ${{ secrets.CHANNEL_PASSKEY }}
          PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
          USER_ID: ${{ secrets.USER_ID }}

