name: Test SDK composer package

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ 7.1, 7.2, 7.3, 7.4, 8.0, 8.1, 8.2 ]

    steps:
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Composer install
        uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php }}

      - name: Run SDK test
        run: |
          cd example/
          php Base.php
